name: Leave Management System
values:
  - key: baseUrl
    value: 'http://localhost:8080'
  - key: userId
    value: '1'
  - key: departmentId
    value: '1'
  - key: leaveTypeId
    value: '1'
  - key: leaveId
    value: '1'
  - key: entityType
    value: LeaveApplication
  - key: entityId
    value: '1'
  - key: userEmail
    value: admin@example.com
  - key: authtoken
    secret: true
