spring.application.name=leave-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/leave_management_db
spring.datasource.username=root
spring.datasource.password=Mysql@1812

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT Configuration

jwt.secret=${JWT_SECRET}

# 24 hours in milliseconds  
jwt.expiration=86400000 

## Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sankarsahu4043@gmail.com
spring.mail.password=fssfbyiswchbgoot

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true